server:
    port: 7000

#spring
spring:
  devtools:
    restart:
      enabled: true        #这里是为了热部署的，与mybatis是无关的
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  sms:
    huyi:
      api_id: C34514978
      api_key: 8815ef0b4173558707b68b002d3e0c44
  mail:
    host: smtp.163.com
    username: m18198539841
    password: gwidknjuxdnkqulc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: 18198539841@163.com
          to: 1129091596@qq.com
        sms:
          to: 18198539841

management:
     security:
        enabled: false